name: C++ Linter and Formatter Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    - name: Check code formatting with clang-format
      run: |
        echo "Running clang-format check..."
        find . \( -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 clang-format -n --Werror

    - name: Run cpplint
      run: |
        echo "Running cpplint..."
        # Запускает скрипт cpplint.py для всех .cpp и .h файлов
        find . \( -name '*.cpp' -o -name '*.h' \) -print0 | xargs -0 python cpplint.py --filter=-legal/copyright,-runtime/int
